### ISSUE TITLE
ModelNotSagaInitializedError raised in test classes

### ISSUE THREAD

**Issue by twheys** [kayak/redux-data-model#4]
Although this exception is very useful when running in the browser, while running a test suite it does not allow a model to be tested without initializing saga middleware and calling `combineModelReducers`.

As a side note, if you only have one model maybe it should not be required to call `combineModelReducers([myOnlyModel])`

```
describe('a successful execution', () => {
    let gen;
    beforeAll(() => {
        gen = testModel.effects.fetchList(action, sagaEffects, actionCreators);
    });
    it('first sets loading=true in the store', () => {
        expect(gen.next().value).toEqual(sagaEffects.put(actionCreators.setListLoading()));
    });
    it('then calls the API endpoint', () => {
        expect(gen.next().value).toEqual(sagaEffects.call(axiosEffects.fetchList, listUrl, action));
    });
    it('then reduces the returned payload in the store and sets loading=false', () => {
        expect(gen.next(mockList).value)
            .toEqual(sagaEffects.put(actionCreators.setList({list: mockList})));
    });
});
```

```
ModelNotReduxInitializedError: Models need to be initialized with combineModelReducers prior to any usage. Now make this the case for: testmodel. See https://kayak.github.io/redux-data-model/docs/api/api-index#error-classes for more info.

    at new ModelNotReduxInitializedError (/Users/theys/r9/AN/dashmore/node_modules/redux-data-model/dist/cjs/index.js:1121:28)
    at Proxy.setListError (/Users/theys/r9/AN/dashmore/node_modules/redux-data-model/dist/cjs/index.js:1534:23)
    at Object.next [as fetchList] (/Users/theys/r9/AN/dashmore/src/standardModel.jsx:166:40)
    at fetchList.next (<anonymous>)
    at Object.it (/Users/theys/r9/AN/dashmore/src/standardModel.test.jsx:203:32)
    at Object.asyncJestTest (/Users/theys/r9/AN/dashmore/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:100:37)
    at resolve (/Users/theys/r9/AN/dashmore/node_modules/jest-jasmine2/build/queueRunner.js:43:12)
    at new Promise (<anonymous>)
    at mapper (/Users/theys/r9/AN/dashmore/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at promise.then (/Users/theys/r9/AN/dashmore/node_modules/jest-jasmine2/build/queueRunner.js:73:41)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

**Comment by twheys** [comment]
workaround
```
const testModel = new Model(...);
testModel._isReduxInitialized = true;
testModel._isSagaInitialized = true;
```

**Comment by x8lucas8x** [comment]
@twheys those are private variables, please use the static prop instead (https://kayak.github.io/redux-data-model/docs/api/classes/api-classes-model#static-disableinitializationchecks). As recommend on https://kayak.github.io/redux-data-model/docs/api/classes/api-classes-modelnotsagainitializederror and https://kayak.github.io/redux-data-model/docs/api/classes/api-classes-modelnotreduxinitializederror. I recommend this to be set on you global test setup script, along with enzime configuration, so that you don't do that on every test.
